# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt autocd
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/mpombo/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

### My stuff below here ###

if ! [[ -f ~/.zsh_alias ]]; then
    echo "Aliases not loaded, ~/.zsh_alias does not exist."
else
    source ~/.zsh_alias
fi

## Plugins!
# I like autosuggestions
autosuggest_file="/usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh"
if ! [[ -f $autosuggest_file ]]; then
    echo "zsh-autosuggestions.zsh not found in $(dirname $autosuggest_file). Install the plugin or consider updating the location in your zshrc."
else
    source $autosuggest_file
fi

# I also like syntax highlighting
syntax_file="/usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
if ! [[ -f $syntax_file ]]; then
    echo "zsh-syntax-highlighting.zsh not found in $(dirname $syntax_file). Install the plugin or consider updating the location in your zshrc."
else
    source $syntax_file
fi

# I'm such a cool guy just look at me go
echo 'Welcome back, Matthew!'
neofetch    # Consult neofetch config files to set colors

# I'm an important guy
export PATH="$PATH:$HOME/.bin:."

## Display git branch in prompt
autoload -Uz vcs_info
precmd() { vcs_info }

# Format vcs_info_msg_0_ variable
zstyle ':vcs_info:git:*' formats '%F{blue}%B(%%b%F{10}%b%F{blue}%B)%%b%f '

# Customize prompt
# Comes after git branch stuff so that I can use the vcs_info variable
setopt PROMPT_SUBST
export PROMPT='${vcs_info_msg_0_}%F{green}%n%f:%F{blue}%2~%f%% '
export RPROMPT='%(0?..%F{red}%?%f)'

