# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt autocd
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/mpombo/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

### My stuff below here ###

[[ -f ~/.zsh_alias ]] && source ~/.zsh_alias

## Plugins!
# I like autosuggestions
source "/usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh"

# I also like syntax highlighting
source "/usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"

# I'm so fucking cool just look at me go
echo 'Welcome back, Matthew!'
neofetch --colors 4 1 10 9 15 7

# I'm an important guy
export PATH="$PATH:$HOME/.bin:."

## Display git branch in prompt
autoload -Uz vcs_info
precmd() { vcs_info }

# Format vcs_info_msg_0_ variable
zstyle ':vcs_info:git:*' formats '%F{blue}%B(%%b%F{10}%b%F{blue}%B)%%b%f '

# Customize prompt
# Comes after git branch stuff so that I can use the vcs_info variable
setopt PROMPT_SUBST
export PROMPT='${vcs_info_msg_0_}%F{green}%n%f:%F{blue}%2~%f%% '
export RPROMPT='%(0?..%F{red}%?%f)'

